const listaProductos = [
    {
      "_id": "663e0cc82ac4f85f90aac1de",
      "codigo": "54321",
      "descripcion": "Sedán elegante",
      "precio": "800000.75",
      "unidadesVendidas": 10,
      "gastoAcumulado": "8000007.5",
      "cantidadAlmacen": 20,
      "umbralSolicitudProveedor": 5,
      "umbralOcultoEnTienda": 0,
      "enOferta": false,
      "descuento": "0",
      "esNovedad": true,
      "valoracionProducto": 4,
      "marca": "Mercedes-Benz",
      "modelo": "Clase E",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1df",
      "codigo": "67890",
      "descripcion": "Todo terreno familiar",
      "precio": "650000.0",
      "unidadesVendidas": 5,
      "gastoAcumulado": "3250000.0",
      "cantidadAlmacen": 15,
      "umbralSolicitudProveedor": 3,
      "umbralOcultoEnTienda": 0,
      "enOferta": true,
      "descuento": "0.15",
      "esNovedad": false,
      "valoracionProducto": 3,
      "marca": "Toyota",
      "modelo": "Land Cruiser",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1e0",
      "codigo": "13579",
      "descripcion": "Compacto urbano",
      "precio": "350000.25",
      "unidadesVendidas": 8,
      "gastoAcumulado": "2800002.0",
      "cantidadAlmacen": 12,
      "umbralSolicitudProveedor": 4,
      "umbralOcultoEnTienda": 0,
      "enOferta": false,
      "descuento": "0",
      "esNovedad": false,
      "valoracionProducto": 5,
      "marca": "Honda",
      "modelo": "Civic",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1e1",
      "codigo": "24680",
      "descripcion": "Monovolumen espacioso",
      "precio": "500000.0",
      "unidadesVendidas": 3,
      "gastoAcumulado": "1500000.0",
      "cantidadAlmacen": 8,
      "umbralSolicitudProveedor": 2,
      "umbralOcultoEnTienda": 0,
      "enOferta": true,
      "descuento": "0.1",
      "esNovedad": false,
      "valoracionProducto": 4,
      "marca": "Volkswagen",
      "modelo": "Touran",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1e2",
      "codigo": "36912",
      "descripcion": "Híbrido eficiente",
      "precio": "600000.5",
      "unidadesVendidas": 6,
      "gastoAcumulado": "3600003.0",
      "cantidadAlmacen": 10,
      "umbralSolicitudProveedor": 3,
      "umbralOcultoEnTienda": 0,
      "enOferta": false,
      "descuento": "0",
      "esNovedad": true,
      "valoracionProducto": 4,
      "marca": "Toyota",
      "modelo": "Prius",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1e3",
      "codigo": "97531",
      "descripcion": "Coupé deportivo",
      "precio": "900000.0",
      "unidadesVendidas": 4,
      "gastoAcumulado": "3600000.0",
      "cantidadAlmacen": 6,
      "umbralSolicitudProveedor": 1,
      "umbralOcultoEnTienda": 0,
      "enOferta": true,
      "descuento": "0.2",
      "esNovedad": false,
      "valoracionProducto": 4,
      "marca": "BMW",
      "modelo": "Serie 4",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1e4",
      "codigo": "951357",
      "descripcion": "SUV lujoso",
      "precio": "1100000.25",
      "unidadesVendidas": 7,
      "gastoAcumulado": "7700001.75",
      "cantidadAlmacen": 14,
      "umbralSolicitudProveedor": 4,
      "umbralOcultoEnTienda": 0,
      "enOferta": false,
      "descuento": "0",
      "esNovedad": false,
      "valoracionProducto": 5,
      "marca": "Audi",
      "modelo": "Q8",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1e5",
      "codigo": "246135",
      "descripcion": "Furgoneta versátil",
      "precio": "750000.0",
      "unidadesVendidas": 3,
      "gastoAcumulado": "2250000.0",
      "cantidadAlmacen": 10,
      "umbralSolicitudProveedor": 2,
      "umbralOcultoEnTienda": 0,
      "enOferta": true,
      "descuento": "0.1",
      "esNovedad": false,
      "valoracionProducto": 4,
      "marca": "Ford",
      "modelo": "Transit",
      "comentarios": ""
    },
    {
      "_id": "663e0cc82ac4f85f90aac1e6",
      "codigo": "369258",
      "descripcion": "Descapotable clásico",
      "precio": "950000.0",
      "unidadesVendidas": 2,
      "gastoAcumulado": "1900000.0",
      "cantidadAlmacen": 5,
      "umbralSolicitudProveedor": 1,
      "umbralOcultoEnTienda": 0,
      "enOferta": false,
      "descuento": "0",
      "esNovedad": false,
      "valoracionProducto": 4,
      "marca": "Chevrolet",
      "modelo": "Corvette",
      "comentarios": ""
    }
  ]
  